name: Checkout Git
on: [push]

jobs:
    checkout-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: list-files
              run: ls -a
            - uses: actions/checkout@v4.1.1
            - name: list-files-after
              run: ls -a
    checkout-git-repo:
        runs-on: ubuntu-latest
        steps:
            - name: list-files
              run: ls -a
            - name: checkout-repo
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list-files-after
              run: ls -a