name: Repository Events
on:
    push:
        branches:
            - main
            - "feature/*"   # matches feature/featA
            - "feature/**"  # matches feature/featA, feature/featB, feature/featA/featB
            - "!feature/featA"
        tags:
            - v1.*          # matches v1.1, v1.2, v1.1.2
            - "!v1.1.1"
        paths:
            - "**.js"
            - "!app.js"
    pull_request:
        types: [opened, assigned, reopened]
    issues: 
        types: [opened]

jobs:
    events:
        runs-on: ubuntu-latest
        steps:
            - run: |
                 echo $GITHUB_SHA
                 echo $GITHUB_REF
            - uses: actions/checkout@v4.1.1