name: Manual Trigger Workflow
on:
    workflow_dispatch:
        inputs:
            string:
                description: A string input
                type: string
                required: true
                default: "Default Value"
            number:
                description: A number input
                type: number
                default: 4
            option:
                description: A options input
                required: true
                default: "Option 3"
                type: choice
                options:
                    - Option 1
                    - Option 2
                    - Option 3
            boolean:
                description: A boolean input
                required: false
                type: boolean
            environment:
                description: "Environment"
                type: environment
                required: true
jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF
            - run: | 
                echo ${{ inputs.string }}
                echo ${{ inputs.number }}
                echo ${{ inputs.option }}
                echo ${{ inputs.boolean }}
                echo ${{ inputs.environment }}