name: Shell and Working directory
on: [push]

jobs:
    shell-and-working-directory:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory and list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    windows-and-working-directory:
        runs-on: windows-latest
        steps:
            - name: Windows
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

